### ISSUE TITLE
"non valid number" error when launching on Mac OS

### ISSUE THREAD

**Issue by costanzasimoncini** [jlohmeier/atlasBREX#3] opened 2020-10-02 14:39 UTC
Hi, 
I am using atlasBREX with FSL version 6.0.3, Bash version 5.0.13, on Mac OS Catalina. I also have ANTs installed. 

First, I cannot open most of the images available in the atlasBREX-master folder (for example Masmoset templates). 
Then, I have the following error when launching the following command: 

$ bash atlasBREX.sh -b bet.nii.gz -nb tplateT2.nii.gz -h T2marmo.nii.gz -f n

============
> atlasBREX [1.3]
============

>> Ven  2 oct 2020 16:36:53 CEST
>> PID: 47501
>> Processing:
> (Temp.) rotating template to match MNI152 orientation 
> (Temp.) rotating target volumes to match MNI152 orientation 
> Atlas mask created using fslmaths (b,0.5,0,0): bet_std_mask.nii.gz
(standard_in) 1: illegal character: N
(standard_in) 1: illegal character: N
(standard_in) 1: parse error
(standard_in) 2: parse error
(standard_in) 1: parse error
(standard_in) 2: parse error
(standard_in) 1: parse error
(standard_in) 2: parse error
atlasBREX.sh: ligne 541 : printf: 5.04980793897138778821: nombre non valable

**Comment by jlohmeier** [comment] 2020-10-31 11:29
Hi,

(1) If you clone the repo via git make sure you're using Git LFS:
https://developer.lsst.io/git/git-lfs.html 

Otherwise, you need to download the sample files individually with your browser.

(2) You can ignore the "(standard_in) 1: parse error" and "(standard_in) 1: illegal character: N". This typically occurs on OSX when the processing time is calculated and it won't affect the results. Will be fixed in the future.

(3) However, the last line "atlasBREX.sh: ligne 541 : printf: 5.04980793897138778821: nombre non valable" appears to be an error. Can you send me the referenced files, so I may reproduce the error?

Best,
Johannes

**Comment by davidmeunier79** [comment] 2020-12-31 09:52
Dear all,
 (I do not open a new issue as this one is not solved yet)
 I am facing the same issue when running atlasBREX 1.1 on a new cluster we are installing, and this error was not present when running on our cluster:
` bash atlasBREX.sh -b NMT_SS.nii.gz -nb NMT.nii.gz -h sub-Riesling_ses-2017_acq-0p4mm_T1w_cropped_noise_corrected_maths.nii.gz -f 0.500000 -wrp 10,10,10 -reg 1 -msk a,0,0 -dil 2 -nrm 1
Standard output:

============
> atlasBREX [1.1]
============

>> mercredi 30 décembre 2020, 16:32:59 (UTC+0100)
>> PID: 32433
>> Processing:
> (Temp.) rotating template to match MNI152 orientation 
> (Temp.) rotating target volumes to match MNI152 orientation 
> Atlas mask created using 3dAutomask (a,0,0): NMT_SS_std_mask.nii.gz
Standard error:
++ 3dAutomask: AFNI version=Debian-18.0.05+git24-gb25b21054~dfsg.1-1~nd100+1 (Jan 23 2018) [64-bit]
++ Authored by: Emperor Zhark
** AFNI converts NIFTI_datatype=64 (FLOAT64) in file NMT_SS_.nii.gz to FLOAT32
     Warnings of this type will be muted for this session.
     Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.
++ Loading dataset NMT_SS_.nii.gz
++ Forming automask
 + Fixed clip level = 0.746118
 + Used gradual clip level = 0.736804 .. 0.789884
 + Number voxels above clip level = 5484446
 + Clustering voxels ...
 + Largest cluster has 5483618 voxels
 + Clustering voxels ...
 + Largest cluster has 5469307 voxels
 + Filled 36787 voxels in small holes; now have 5506094 voxels
 + Filled 303099 voxels in large holes; now have 5809193 voxels
 + Clustering voxels ...
 + Largest cluster has 5809193 voxels
 + Clustering non-brain voxels ...
 + Clustering voxels ...
 + Largest cluster has 15699602 voxels
 + Mask now has 5809193 voxels
++ 5809193 voxels in the mask [out of 21508795: 27.01%]
++ first   8 x-planes are zero [from L]
++ last    8 x-planes are zero [from R]
++ first  20 y-planes are zero [from P]
++ last   28 y-planes are zero [from A]
++ first  33 z-planes are zero [from I]
++ last   29 z-planes are zero [from S]
++ Output dataset ./NMT_SS_std_mask.nii.gz
++ CPU time = 0.000000 sec
atlasBREX.sh: ligne 470 : printf: 9.011984120: nombre non valable
Return code: 1
`

**Comment by jlohmeier** [comment] 2020-12-31 18:50
Hi David,

Would you mind sending me the 3 referenced NIFTI files, so I can reproduce the error?

Best,

Johannes

**Comment by davidmeunier79** [comment] 2021-01-04 13:55
Dear @jlohmeier , the problem was very specific to the way our default settings is with numeric, in France we use comma "," instead of point "." to seperate decimals and units... 
I solved the issue by adding "export LC_NUMERIC=C" for whoever may come with a similar problem. Many thanks for your help anyway, and thanks again for AtlasBREX, we make great use of it!

**Comment by jlohmeier** [comment] 2021-01-12 13:57
Thanks - I will add this!

**Closed as completed by jlohmeier** 2021-01-12 13:57 UTC
